### ISSUE TITLE
Make available via NPM

### ISSUE THREAD

**Issue by gabeins** [kareemf/angular-uri#3]
Please? :smile:

**Comment by kareemf** [comment]
@gabrielizaias 
~~Should be up. Reran `bower register angular-uri git@github.com:kareemf/angular-uri.git` to be sure. Running `bower install angular-uri` yielded the desired results. Let me know if you are still having issues.~~

EDIT: I totally spaced and read what I wanted to hear ("Bower" instead of "NPM"). Will update as soon as I get the chance

**Comment by gabeins** [comment]
I think you misunderstood me. I think it'd be nice to have this package available on npm as well as Bower. They are different package managers.

I'd like to run `npm install angular-uri` and have it on my project since I'm not using Bower. For that to be possible, these steps should be followed: https://docs.npmjs.com/getting-started/publishing-npm-packages

Also, Bower is dying a slow death and the recommendation is to switch to npm:
https://twitter.com/desandro/status/667417871799164928

**Comment by kareemf** [comment]
@gabrielizaias 
https://www.npmjs.com/package/angular-uri
Thanks for the prod
